import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "sonner";
import DesignerContextProvider from "@/components/context/DesignerContext";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import NextTopLoader from "nextjs-toploader"
const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      <DesignerContextProvider>
        <NextTopLoader/>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <SessionAuthProvider>  
            {children}</SessionAuthProvider>
            <Toaster></Toaster>
          </ThemeProvider>
          </DesignerContextProvider>
      </body>
    </html>
  );
}
