version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_universidad
    environment:
      POSTGRES_DB: universidad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4dm1n
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: springboot_universidad
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/universidad
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 4dm1n
    ports:
      - "8080:8080"
    restart: always
    entrypoint: ["sh", "-c", "sleep 20 && java -jar app.jar"]

volumes:
  db_data: